name: Gerar MCAddon Automático
on:
  push:
    branches:
      - main  # Toda vez que você salvar algo na branch main, ele cria o arquivo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Criar Pacote .mcaddon
        run: |
          # Este comando zipa as pastas BP e RP juntas no formato que o Minecraft aceita
          zip -r meu_addon_projeto.mcaddon BP RP

      - name: Disponibilizar para Download
        uses: actions/upload-artifact@v4
        with:
          name: Addon_Instalavel
          path: meu_addon_projeto.mcaddon
