name: Publicar Addon

on:
  push:
    tags:
      - 'v*' # O robô vai rodar sempre que você criar uma tag (ex: v1.0)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar Pacotes Separados
        run: |
          # Criando o Behavior Pack (.mcpack)
          cd BP && zip -r ../MeuAddon_BP.mcpack * && cd ..
          
          # Criando o Resource Pack (.mcpack)
          cd RP && zip -r ../MeuAddon_RP.mcpack * && cd ..
          
          # Criando o Addon Completo (.mcaddon)
          zip -r MeuAddon_Completo.mcaddon BP RP

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            MeuAddon_BP.mcpack
            MeuAddon_RP.mcpack
            MeuAddon_Completo.mcaddon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
